trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: windows-latest

steps:
  - script: echo This pipeline runs for all pull requests

  - task: AdvancedSecurity-Dependency-Scanning@1

  - task: AdvancedSecurity-Publish@1
