trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: windows-latest

steps:
  - script: echo This pipeline runs for all pull requests

  - task: AdvancedSecurity-Dependency-Scanning@1

  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: 'csharp, javascript'

  - task: AdvancedSecurity-Codeql-Autobuild@1
  
  - task: AdvancedSecurity-Codeql-Analyze@1
    
  - task: AdvancedSecurity-Publish@1
  
