trigger:
- main

variables:
  resource-group: "ghazdo-workshops"
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"
  webapp_name: tailwind-github-demo
  advancedsecurity.submittoadvancedsecurity: true

pool:
  vmImage: windows-latest

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 
    displayName: 'Build on Windows'
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 10.16.3'
      inputs:
        versionSpec: 10.16.3

    # - task: AdvancedSecurity-Dependency-Scanning@1
    #   displayName: 'Dependency Scanning'
    
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: TailwindTraders.Website/Source/Tailwind.Traders.Web/ClientApp
        verbose: false

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(Parameters.RestoreBuildProjects)'

# qetza.replacetokens.replacetokens-task.replacetokens
    - task: qetza.replacetokens.replacetokens-task.replacetokens
      displayName: 'Replace tokens in files'
      inputs:
        targetFiles: '**/*.dialog'
        encoding: 'auto'
        tokenPattern: 'custom'
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        verbosity: 'detailed'
        keepToken: false

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(Parameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: AdvancedSecurity-Dependency-Scanning@1
      displayName: 'Dependency Scanning'
      
    - task: AdvancedSecurity-Publish@1
      displayName: 'Dependency Publish'
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(Parameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'
